name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Create output directory
        run: mkdir -p dist

      - name: Build for Windows x64
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          mkdir -p dist/windows-x64
          go build -o dist/windows-x64/go-srtla.exe

      - name: Build for macOS ARM64
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          mkdir -p dist/macos-arm64
          go build -o dist/macos-arm64/go-srtla

      - name: Build for Linux x64
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p dist/linux-x64
          go build -o dist/linux-x64/go-srtla

      - name: Build for Linux ARM64
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          mkdir -p dist/linux-arm64
          go build -o dist/linux-arm64/go-srtla

      - name: Make binaries executable
        run: |
          chmod +x dist/macos-arm64/go-srtla
          chmod +x dist/linux-x64/go-srtla
          chmod +x dist/linux-arm64/go-srtla

      - name: Create ZIP archives
        run: |
          cd dist
          zip -r go-srtla-windows-x64.zip windows-x64/
          zip -r go-srtla-macos-arm64.zip macos-arm64/
          zip -r go-srtla-linux-x64.zip linux-x64/
          zip -r go-srtla-linux-arm64.zip linux-arm64/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/go-srtla-windows-x64.zip
            dist/go-srtla-macos-arm64.zip
            dist/go-srtla-linux-x64.zip
            dist/go-srtla-linux-arm64.zip
          draft: false
          prerelease: false
